### ISSUE TITLE
fd can get stuck when ran onto the whole FS from the root

### ISSUE THREAD

**Issue by Porkepix** [sharkdp/fd#288]
The ran command is just `fd foobar /`. It gets stuck and never end. I sadly was unable to understand what's causing it.
I can investigate to give answers if you have some ideas about what else could I check.

Below is the partition's setup:

```
# lsblk
NAME           MAJ:MIN RM   SIZE RO TYPE  MOUNTPOINT
sda              8:0    0 223,6G  0 disk  
├─sda1           8:1    0   512M  0 part  /boot/efi
├─sda2           8:2    0   200M  0 part  
│ └─cryptboot  254:3    0   198M  0 crypt /boot
└─sda3           8:3    0 222,9G  0 part  
  └─lvm        254:0    0 222,9G  0 crypt 
    ├─vg0-swap 254:1    0     8G  0 lvm   [SWAP]
    └─vg0-root 254:2    0 214,9G  0 lvm   /
```

EDIT: Issue is reproducing everytime on this Archlinux setup. Couldn't reproduce it on another Archlinux with unencrypted system.

**Comment by sharkdp** [comment]
I can reproduce this on my PC. This seems to be a permission problem with files in `/proc` and `/sys`.

Could you try to run
```
fd -E /proc -E /sys foobar /
```
where `-E` (`--exclude`) excludes these two folders?

**Comment by Porkepix** [comment]
Indeed this does work. Strange that my personal server doesn't have the same issue though.

**Comment by Porkepix** [comment]
Oh, and the issue was present even when running fd as root. So I'm not sure about the permission idea.

**Comment by sharkdp** [comment]
> Oh, and the issue was present even when running fd as root. So I'm not sure about the permission idea.

I see, interesting. Something else must be going on inside `/proc` and/or `/sys`. If anybody has an idea on how to fix this, I'd be glad for any hints.

**Comment by Porkepix** [comment]
Even more interesting.
`fd -E "/proc/[0-9]*" foobar /` is succeeding.
`fd -E "/proc/[0-9]*" foobar /proc` is failing.

**Comment by sharkdp** [comment]
Wait, this also seems to change from time to time. Right now, `fd foobar /` works perfectly fine on my machine(?!?).

**Comment by sharkdp** [comment]
I suspect this could be caused by infinite recursion within `/proc` (see [here](https://stackoverflow.com/q/4740818/704831) or [here](https://stackoverflow.com/q/20914606/704831)).

Unfortunately, I cannot reproduce the problem at the moment.

**Comment by sharkdp** [comment]
I'm going to close this (for now), as there is no further feedback.

The workaround for now is to explicitly exclude `/proc` via

```
fd -E /proc ...
```

**Comment by Porkepix** [comment]
Sorry, didn't knew you was waiting for input: it was added with an edit, so I wasn't notified: original comment was not asking for input. Please post a new comment in such situation.

I tested what you asked for: didn't solved the issue, so I guess this isn't infinite recursion.
And while it hang like that, CPU is using every single core at 100%.

I guess we could then reopen it?

**Comment by Porkepix** [comment]
By the way, this was on Linux computers.
I'm currently running it on an old mac. I guess it's gonna take long (old, bad shaped HDD, no SSD in it), so I'll let it run, but I think that when I'll be back this evening computer will be brozen with out of memory: currently running for like 10 minutes, CPU is only around 10%, but memory constantly increase. It started low and currently is already at 140MB.

**Comment by Porkepix** [comment]
So, not reproduced on the mac, it just took quite some time.

**Comment by sharkdp** [comment]
Thank you for investigating.

To summarize (correct me if I'm wrong):

- `fd` can get stuck in an infinite (or very long?) loop when searching `/`.
- This seems to be caused by something weird going on in `/proc`.
- The problem is not 100% reproducible (I'm pretty sure I saw this on my Linux machine, but I can not reproduce it now - nor on three other Linux machines).
- The problem can be prevented by excluding `/proc` or `/proc/[0-9]*`.

**Comment by Porkepix** [comment]
Well, that's pretty much it except that I detected a weird case in comment https://github.com/sharkdp/fd/issues/288#issuecomment-383637131
It looks like excluding `/proc/[0-9]*` and searching in `/` make it work but excluding the same thing and searching in `/proc`make it fail… which is pure nonsense to me. I was trying the find if there was a culprit file and stopped when I discovered that because that didn't make any sense.

The exact same computer I did the tests on yesterday morning now succeed on `fd foobar /`… I'll try to test the other one that had issue when coming to work.

**Comment by sharkdp** [comment]
> Do you have any idea how to debug that? See where does it hang like that?

Maybe `fd . /`?

> And this is kinda out of topic, but per comment #288 (comment) is it normal that on the mac case memory did increase during the whole search process?

I'm not sure, I will look into it.

**Comment by Porkepix** [comment]
Okay, so running `fd . /` on the desktop computer reliably fail on `/proc/11364/task/11364/net
`.
That process is a Firefox one: `clement  11364  0.0  0.0      0     0 ?        Z    10:22   0:00 [firefox] <defunct>

The laptop's case however is more complicated. It seems to stop randomly on any file at some point. I can share some of them here if you think that's useful but I'm not sure about that. Maybe a doing single thread might help. Don't know why one computer is affected while the other isn't though.

**Comment by Porkepix** [comment]
Okay, actually I just RTFM'd a bit and used `-j 1`.

Got stuck on `/proc/19848/net`

`ps aux` give that:
`clement  19848  0.0  0.0      0     0 ?        Z    08:46   0:00 [pingsender] <defunct>`

**Comment by Porkepix** [comment]
Oh, and surprisingly, using `-j 1` still shows two processes. Both use 100% of the CPU.

And last thing but I've no idea about: sometimes when the bug triggers it "breaks" the terminal I used, terminology. ie. display was still refreshed, but I couldn't type anymore, even when I opened new windows. Only happened one time or two, and got fixed when I pkill'd the process from elsewhere.

**Comment by sharkdp** [comment]
Thank you very much for your investigation!

It looks like you are up to something with the `<defunct>` processes! I can now reliably reproduce this by creating a zombie process on purpose:

1. Run `fd foobar /proc` => everything is fine
2. Copy the code from https://stackoverflow.com/a/25228579/704831 into a file called `zombie.c`
3. Compile it: `gcc -o zombie zombie.c`.
4. Create the zombie process: `./zombie`.
5. Run `ps -ef | grep defunct` in a new terminal. It should show `[zombie] <defunct>`.
6. Run `fd foobar /proc` while `zombie` is still running. It will hang.
7. Stop `zombie` and run `fd foobar /proc` again => everything is fine.

Experiment 2:

1. Create the zombie process: `./zombie`.
2. Run `fd foobar /` => everything ok
3. Get the PID of the defunct process via `ps -ef | grep defunct`
4. Call `fd foobar / -E $PID` => everything ok
5. Call `fd foobar /` => it hangs

**Comment by sharkdp** [comment]
(see the linked ticked in ripgrep for some further debugging)

**Comment by sharkdp** [comment]
This might be a bug in the `ReadDir` iterator in Rusts standard library. The issue has been reported here: https://github.com/rust-lang/rust/issues/50619

**Comment by sharkdp** [comment]
My pull request which fixes a bug in Rusts standard library has been merged (https://github.com/rust-lang/rust/pull/50630). Now we have to wait for the next Rust release in order to fix this bug in `fd`.

**Comment by sharkdp** [comment]
Actually, we have to wait for Rust 1.29. I forgot about the beta stage. This bug is fixed when compiling `fd` with the current `rustc 1.29.0-beta.1`.

**Comment by sharkdp** [comment]
This is finally fixed! :sparkles:

**Comment by sharkdp** [comment]
Fix released in [fd-7.2.0](https://github.com/sharkdp/fd/releases/tag/v7.2.0).

**Comment by monkeyt00l** [comment]
This issue seems to still exist on version 8.6.0

Running "cd /proc && fd teststring" will make fd freeze and use up all cpu cores (until I cancelled the operation after a minute)

**Comment by tavianator** [comment]
Interesting, I can't reproduce that locally.  `fd -L` hangs, but that's somewhat expected since `/proc/self/root` is a symlink to `/`.  Do you possibly have an alias like `fd=fd -L`?

Otherwise, does it still reproduce with `fd -j1`?  Can you paste some of the output of `cd /proc && strace -f fd` once it hangs?

**Comment by monkeyt00l** [comment]
Running 'fd -j1' will list files until it stopped at 24677/map_files/
24677 was the process id of firefox (/usr/lib/firefox/firefox -contentproc)

I suspect this may have to do with the sandboxing features in firefox, since it also uses seccomp and blocks ptrace. 
Other sandboxed apps behave similarly and for any process that uses seccomp, I usually need root privileges to do something like 'lsof -p <pid>' 

However, this one seems to be unreliable to reproduce sicne it I could not reproduce it on a clean test install

The strace log shows a bunch of logs that repeats endlessly https://gist.github.com/monkeyt00l/30a2bdcd3544db3fbc896acc934bbc30

The pids in the log also seem to belong to firefox content processes

**Comment by tmccombs** [comment]
Hmm, from looking at the strace output I wonder if this is related to #1186 . It seems like in both cases fd is getting stuck in an infinite loop due to an error (in this case, a permission error).

**Comment by tavianator** [comment]
I hope so!  EACCES is much easier to debug than EIO :)

**Comment by tavianator** [comment]
I can reproduce this now:

```console
tavianator@graphene$ (sleep 1& (sleep 2 && fd . /proc/${!}/net --show-errors)& exec /bin/sleep 3)
[fd error]: Invalid argument (os error 22)
[fd error]: Invalid argument (os error 22)
[fd error]: Invalid argument (os error 22)
[fd error]: Invalid argument (os error 22)
[fd error]: Invalid argument (os error 22)
[fd error]: Invalid argument (os error 22)
[fd error]: Invalid argument (os error 22)
[fd error]: Invalid argument (os error 22)
[fd error]: Invalid argument (os error 22)
[fd error]: Invalid argument (os error 22)
...
```

That command creates a zombie process (the `sleep 1)` by replacing the shell with a command that won't `wait()` for its children (the `exec /bin/sleep 3`).  In the meantime, we wait for the zombie to die and then run `fd` in its `/proc/<PID>/net` directory.  For a zombie process, the `open()` will succeed but `readdir()` will fail with `EINVAL`.  This is key to triggering the error.

Those with a long memory might remember the bug https://github.com/rust-lang/rust/issues/50619, which @sharkdp filed and then [fixed](https://github.com/rust-lang/rust/pull/50630) as a result of **this bug**.

Unfortunately, some silly programmer named @tavianator reintroduced the bug in https://github.com/rust-lang/rust/pull/92778.  Or to be a little more charitable, the original fix only applied to some platforms, of which Linux used to be one.  But now Linux uses a different `ReadDir` implementation that is better in many ways but regressed this bug.  Oops!

I guess I'll fix it in Rust, unless someone beats me to it.

**Comment by tavianator** [comment]
Here's the fix: https://github.com/rust-lang/rust/pull/105638

**Comment by sharkdp** [comment]
So if I understand correctly, your PR landed in Rust 1.60. Which is precisely our MSRV right now :smile:. So there's currently no way to fix this bug by compiling with an older version of `rustc`, unless we backport `fd` to `1.27 <= MSRV < 1.60`. Which might not be a big deal maybe.

**Comment by tmccombs** [comment]
clap 4.0 has an MSRV of 1.60, so we'd probably have to downgrade clap to 3.x again if we did that.

**Comment by tavianator** [comment]
Alternatively we can work around it in `ignore` by adding

```rust
if result.is_err() {
    break;
}
```

here: https://github.com/BurntSushi/ripgrep/blob/515f120b5c2c7984c8dfa8bafeda42916457b0ba/crates/ignore/src/walk.rs#L1497-L1507

**Comment by tavianator** [comment]
Did that: https://github.com/BurntSushi/ripgrep/pull/2378

**Comment by johnalanwoods** [comment]
I'm now seeing this issue on macOS, with the latest release `fd 10.1.0` - should I open a new ticket?

**Comment by sharkdp** [comment]
> I'm now seeing this issue on macOS, with the latest release `fd 10.1.0` - should I open a new ticket?

That'd be great.

**Comment by johnalanwoods** [comment]
Apols, resolved this on my side, it was a heavily under performing disk.
